# PHP CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.9-fpm-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Update composer
          command: sudo composer self-update
      - run:
          name: Install dependencies
          command: composer install -o --prefer-dist --no-interaction

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: Install xDebug
          command: pecl install xdebug && docker-php-ext-enable xdebug
      - run:
          name: Prepare log directories
          command: mkdir -p build/logs/coverage
      - run:
          name: Run unit tests
          command: vendor/bin/phpunit.phar -c build

      - store_artifacts:
          path: build/logs/coverage
          destination: code-coverage-html
